sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1.3

env:
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=3.*
  - SYMFONY_VERSION=4.*

matrix:
  exclude:
    - php: 5.5
      env: SYMFONY_VERSION=4.*
    - php: 5.6
      env: SYMFONY_VERSION=4.*
    - php: 7.0
      env: SYMFONY_VERSION=4.*

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer self-update

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source
  - composer install --prefer-source

script:
  - ./bin/phpunit --coverage-text

notifications:
  email:
    - thomas@tourlourat.com
