sudo: false
dist: bionic
language: php

php:
  - "7.2"
  - "7.3"
  - "7.4"
  - "8.0"
  - "8.1.0"

env:
  - SYMFONY_VERSION=3.*
  - SYMFONY_VERSION=4.*
  - SYMFONY_VERSION=5.*

cache:
  directories:
    - $HOME/.composer/cache

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer self-update

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer require symfony/console:${SYMFONY_VERSION} symfony/framework-bundle:${SYMFONY_VERSION} symfony/http-kernel:${SYMFONY_VERSION} --prefer-source
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-source

script:
  - XDEBUG_MODE=coverage ./bin/phpunit --coverage-text

notifications:
  email:
    - thomas@tourlourat.com
